version: "3.9"
services:
  redis:
    image: redis:6.0
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules


    
